import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { z } from 'zod';
import { Search as SearchIcon, ArrowRight } from 'lucide-react';
import { type FormEvent } from 'react';
import { PageHeader } from '@/components/campus/layout';
import { pageHead } from '@/components/campus/seo';
import { EventCard, ResourceCard, ClubCard, AnnouncementCard, LocationCard, EmptyState } from '@/components/campus/cards';
import { events,resources,clubs,announcements,locations } from '@/data/campus';
import { Button } from '@/components/ui/button';
export const Route=createFileRoute('/search')({validateSearch:z.object({q:z.string().catch('')}),head:()=>pageHead('Search Campus','Search campus events, resources, clubs, announcements and locations.','/search'),component:SearchPage});
function SearchPage(){const {q}=Route.useSearch();const navigate=useNavigate();const term=q.trim().toLowerCase();const groups=[{title:'Events',to:'/events' as const,items:events.filter(x=>`${x.title} ${x.category} ${x.description} ${x.venue}`.toLowerCase().includes(term)),render:(item:typeof events[number])=><EventCard key={item.id} item={item}/>},{title:'Resources',to:'/resources' as const,items:resources.filter(x=>`${x.title} ${x.category} ${x.subject} ${x.description}`.toLowerCase().includes(term)),render:(item:typeof resources[number])=><ResourceCard key={item.id} item={item}/>},{title:'Clubs',to:'/clubs' as const,items:clubs.filter(x=>`${x.name} ${x.category} ${x.description}`.toLowerCase().includes(term)),render:(item:typeof clubs[number])=><ClubCard key={item.id} item={item}/>},{title:'Announcements',to:'/announcements' as const,items:announcements.filter(x=>`${x.title} ${x.category} ${x.description}`.toLowerCase().includes(term)),render:(item:typeof announcements[number])=><AnnouncementCard key={item.id} item={item}/>},{title:'Campus Locations',to:'/directory' as const,items:locations.filter(x=>`${x.name} ${x.category} ${x.building} ${x.description}`.toLowerCase().includes(term)),render:(item:typeof locations[number])=><LocationCard key={item.id} item={item}/>}];function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();navigate({to:'/search',search:{q:new FormData(e.currentTarget).get('q')?.toString()||''}})}return <><PageHeader eyebrow="Campus search" title="Find what you’re looking for." description="One search across campus events, learning resources, clubs, updates and places."/><main className="page-wrap py-10"><form role="search" onSubmit={submit} className="flex max-w-2xl gap-2"><input key={q} name="q" type="search" defaultValue={q} aria-label="Search all campus content" placeholder="Search campus resources..." className="field flex-1"/><Button type="submit" className="h-11"><SearchIcon/> <span className="hidden sm:inline">Search</span></Button></form>{!term?<p className="mt-8 text-sm text-muted-foreground">Start typing to explore everything on campus.</p>:<><p className="mt-8 text-sm text-muted-foreground">Results for “{q}”</p>{groups.every(g=>g.items.length===0)?<EmptyState query={q}/>:groups.map(group=><section key={group.title} className="mt-10"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-2xl font-semibold">{group.title} <span className="text-base font-normal text-muted-foreground">({group.items.length})</span></h2><Button variant="link" asChild><Link to={group.to}>Explore all <ArrowRight/></Link></Button></div>{group.items.length?<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{group.items.slice(0,3).map(item=>(group.render as (item: typeof item)=>React.ReactNode)(item))}</div>:<p className="border-b border-border pb-5 text-sm text-muted-foreground">No matching {group.title.toLowerCase()}.</p>}</section>)}</>}</main></>}
