import { Link } from '@tanstack/react-router';
import { ArrowRight, Bookmark, CalendarDays, Clock3, Download, MapPin, Users, BookOpen, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { useState } from 'react';
import { events, type Event, type Resource, type Club, type Announcement, type Location } from '@/data/campus';
import techImage from '@/assets/event-tech.jpg';
import cultureImage from '@/assets/event-culture.jpg';

export function BookmarkButton({ label }: { label: string }) {
  const [saved, setSaved] = useState(false);
  return <Button type="button" variant="outline" size="icon" title={saved ? `Remove ${label} from bookmarks` : `Bookmark ${label}`} aria-label={saved ? `Remove ${label} from bookmarks` : `Bookmark ${label}`} aria-pressed={saved} onClick={() => setSaved(!saved)} className={saved ? 'text-primary border-primary' : ''}><Bookmark className={saved ? 'fill-current' : ''}/></Button>;
}
export function EventCard({ item }: { item: Event }) {
  return <article className="group overflow-hidden rounded-lg border border-border bg-card transition-all hover:-translate-y-0.5 hover:shadow-card">
    <div className="relative h-44 overflow-hidden"><img src={item.image === 'tech' ? techImage : cultureImage} alt={item.image === 'tech' ? 'Students collaborating at a campus technology event' : 'Students performing at a campus cultural event'} width={1024} height={680} loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/><span className="absolute left-4 top-4 rounded bg-card px-2.5 py-1 text-xs font-semibold text-foreground">{item.category}</span></div>
    <div className="p-5"><div className="mb-3 flex items-center justify-between gap-2"><span className="text-xs font-semibold text-primary">{item.status}</span><BookmarkButton label={item.title}/></div><h3 className="font-display text-xl font-semibold leading-snug">{item.title}</h3><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-relaxed text-muted-foreground">{item.description}</p><div className="mt-4 space-y-2 text-xs text-muted-foreground"><p className="flex items-center gap-2"><CalendarDays size={15}/>{formatDate(item.date)} · {item.time}</p><p className="flex items-center gap-2"><MapPin size={15}/>{item.venue}</p></div><EventDetail item={item}/></div>
  </article>;
}
export function EventDetail({ item }: { item: Event }) { const [interested, setInterested] = useState(false); return <Dialog><DialogTrigger asChild><Button variant="outline" className="mt-5 w-full">View details <ArrowRight/></Button></DialogTrigger><DialogContent className="max-w-lg"><DialogHeader><span className="text-xs font-semibold uppercase text-primary">{item.category} · {item.status}</span><DialogTitle className="font-display text-2xl">{item.title}</DialogTitle><DialogDescription>{item.description}</DialogDescription></DialogHeader><div className="space-y-3 border-y border-border py-4 text-sm"><p className="flex items-center gap-2"><CalendarDays size={17}/>{formatDate(item.date)} · {item.time}</p><p className="flex items-center gap-2"><MapPin size={17}/>{item.venue}</p><p className="flex items-center gap-2"><Users size={17}/>{item.organizer}</p></div><Button onClick={() => setInterested(true)} disabled={interested}>{interested ? 'Interest noted for this preview' : 'Register interest'}</Button><p className="text-xs text-muted-foreground">Preview only — no registration is submitted.</p></DialogContent></Dialog> }
export function ResourceCard({ item }: { item: Resource }) { return <article className="flex flex-col rounded-lg border border-border bg-card p-5 transition-all hover:-translate-y-0.5 hover:shadow-card"><div className="flex justify-between gap-3"><div className="flex size-11 items-center justify-center rounded-md bg-secondary text-primary"><BookOpen size={21}/></div><BookmarkButton label={item.title}/></div><span className="mt-5 text-xs font-semibold text-primary">{item.category}</span><h3 className="mt-2 font-display text-lg font-semibold leading-snug">{item.title}</h3><p className="mt-2 flex-1 text-sm leading-relaxed text-muted-foreground">{item.description}</p><p className="mt-5 text-xs text-muted-foreground">{item.subject} · {item.semester}</p><div className="mt-4 border-t border-border pt-4"><Dialog><DialogTrigger asChild><Button variant="outline" className="w-full">View resource <ExternalLink/></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{item.title}</DialogTitle><DialogDescription>{item.description}</DialogDescription></DialogHeader><div className="space-y-2 text-sm"><p><strong>Type:</strong> {item.type}</p><p><strong>Subject:</strong> {item.subject}</p><p><strong>Level:</strong> {item.semester}</p></div><p className="border-t border-border pt-4 text-sm text-muted-foreground">This is a sample listing. A file will be available when the resource library is connected.</p></DialogContent></Dialog></div></article> }
export function ClubCard({ item }: { item: Club }) { return <article className="flex flex-col rounded-lg border border-border bg-card p-5 transition-all hover:-translate-y-0.5 hover:shadow-card"><div className="flex items-center gap-4"><div className="flex size-14 shrink-0 items-center justify-center rounded-md bg-secondary font-display text-lg font-bold text-primary" aria-hidden="true">{item.initials}</div><span className="text-xs font-semibold text-primary">{item.category}</span></div><h3 className="mt-5 font-display text-xl font-semibold">{item.name}</h3><p className="mt-2 flex-1 text-sm leading-relaxed text-muted-foreground">{item.description}</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Users size={15}/>{item.members} members</span><span className="flex items-center gap-1.5"><Clock3 size={15}/>{item.meeting}</span></div><Dialog><DialogTrigger asChild><Button variant="outline" className="mt-5 w-full">View club <ArrowRight/></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{item.name}</DialogTitle><DialogDescription>{item.description}</DialogDescription></DialogHeader><p className="text-sm">{item.category} · {item.members} members</p><p className="text-sm">Meets {item.meeting}</p><p className="text-sm text-muted-foreground">Club membership and contact details will be available when campus services are connected.</p></DialogContent></Dialog></article> }
export function AnnouncementCard({ item }: { item: Announcement }) { return <article className="rounded-lg border border-border bg-card p-5 transition-colors hover:border-primary/40"><div className="flex flex-wrap items-center gap-2 text-xs"><span className="font-semibold text-primary">{item.category}</span><span className="text-muted-foreground">· {formatDate(item.date)}</span><span className="ml-auto rounded bg-secondary px-2 py-1 font-medium text-secondary-foreground">{item.priority}</span></div><h3 className="mt-4 font-display text-lg font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{item.description}</p><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="text-xs text-muted-foreground">{item.department}</span><Dialog><DialogTrigger asChild><Button variant="link" className="h-auto p-0">Read more <ArrowRight/></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{item.title}</DialogTitle><DialogDescription>{item.department} · {formatDate(item.date)} · {item.priority}</DialogDescription></DialogHeader><p className="text-sm leading-relaxed">{item.description} {item.details}</p></DialogContent></Dialog></div></article> }
export function LocationCard({ item }: { item: Location }) { return <article className="flex flex-col rounded-lg border border-border bg-card p-5 transition-all hover:-translate-y-0.5 hover:shadow-card"><span className="text-xs font-semibold text-primary">{item.category}</span><h3 className="mt-3 font-display text-xl font-semibold">{item.name}</h3><p className="mt-2 flex-1 text-sm leading-relaxed text-muted-foreground">{item.description}</p><div className="mt-5 space-y-2 text-xs text-muted-foreground"><p className="flex items-center gap-2"><MapPin size={15}/>{item.building}</p><p className="flex items-center gap-2"><Clock3 size={15}/>{item.hours}</p></div><Dialog><DialogTrigger asChild><Button variant="outline" className="mt-5 w-full">View details <ArrowRight/></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{item.name}</DialogTitle><DialogDescription>{item.description}</DialogDescription></DialogHeader><p className="text-sm">{item.detail}</p><p className="text-sm text-muted-foreground">{item.building} · {item.hours}</p></DialogContent></Dialog></article> }
export function formatDate(date: string) { return new Date(`${date}T12:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}); }
export function EmptyState({ query }: { query?: string }) { return <div className="py-16 text-center"><p className="font-display text-xl font-semibold">Nothing found just yet</p><p className="mt-2 text-sm text-muted-foreground">{query ? `No matches for “${query}”. Try a different search or filter.` : 'Try another category to see more results.'}</p></div> }
export function SectionHeading({ eyebrow, title, to, linkLabel }: { eyebrow?: string; title: string; to?: '/events'|'/resources'|'/clubs'|'/announcements'|'/directory'; linkLabel?: string }) { return <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div>{eyebrow && <p className="mb-2 text-xs font-semibold uppercase text-primary">{eyebrow}</p>}<h2 className="font-display text-2xl font-semibold sm:text-3xl">{title}</h2></div>{to && <Button variant="link" asChild className="px-0"><Link to={to}>{linkLabel || 'View all'} <ArrowRight/></Link></Button>}</div> }
export function SearchInput({ placeholder = 'Search campus resources...', defaultValue = '', name = 'q' }: { placeholder?: string; defaultValue?: string; name?: string }) { return <div className="relative"><label className="sr-only" htmlFor={`search-${name}`}>{placeholder}</label><input id={`search-${name}`} type="search" name={name} defaultValue={defaultValue} placeholder={placeholder} className="h-11 w-full rounded-md border border-input bg-background px-4 text-sm outline-none placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring"/></div> }
export function CategoryFilter({ categories, active, onChange }: { categories: string[]; active: string; onChange: (category:string)=>void }) { return <div className="flex gap-2 overflow-x-auto pb-2" role="group" aria-label="Filter by category">{['All',...categories].map(category=><Button key={category} type="button" variant={active===category?'default':'outline'} size="sm" aria-pressed={active===category} className="shrink-0" onClick={()=>onChange(category)}>{category}</Button>)}</div> }
export const quickLinks = [{label:'Campus directory',to:'/directory' as const,description:'Find your way around'},{label:'Study resources',to:'/resources' as const,description:'Notes, guides & more'},{label:'Upcoming events',to:'/events' as const,description:'See what’s happening'},{label:'Latest updates',to:'/announcements' as const,description:'Stay in the loop'}];
export { events };
