import { Link, useNavigate } from '@tanstack/react-router';
import { Search, Menu, X, ArrowUpRight, Instagram, Linkedin, Github } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';

const nav = [{label:'Home',to:'/' as const},{label:'Events',to:'/events' as const},{label:'Resources',to:'/resources' as const},{label:'Clubs',to:'/clubs' as const},{label:'Announcements',to:'/announcements' as const}];
export function Brand({ inverse = false }: { inverse?: boolean }) { return <Link to="/" className={`flex items-center gap-2.5 font-display text-xl font-bold tracking-normal ${inverse ? "text-footer-foreground" : "text-foreground"}` } aria-label="CampusFlow home"><span className="flex size-9 items-center justify-center rounded-md bg-primary text-lg font-bold text-primary-foreground">C<span className="text-highlight">.</span></span>CampusFlow</Link> }
export function SiteHeader() {
  const [open,setOpen]=useState(false);
  const navigate=useNavigate();
  function search(e:FormEvent<HTMLFormElement>){e.preventDefault(); const q=new FormData(e.currentTarget).get('q')?.toString().trim(); navigate({to:'/search',search:{q:q||''}});setOpen(false)}
  return <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur-sm"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between gap-5 px-5 sm:px-8"><Brand/><nav aria-label="Primary navigation" className="hidden items-center gap-7 lg:flex">{nav.map(n=><Link key={n.to} to={n.to} activeProps={{className:'text-primary font-semibold'}} className="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground">{n.label}</Link>)}</nav><div className="hidden items-center gap-3 md:flex"><form onSubmit={search} role="search" className="relative"><label className="sr-only" htmlFor="header-search">Search campus resources</label><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input id="header-search" name="q" placeholder="Search campus resources..." className="h-9 w-48 rounded-md border border-input bg-secondary pl-9 pr-3 text-xs outline-none focus-visible:ring-2 focus-visible:ring-ring xl:w-58"/></form><Button variant="outline" size="sm" title="Login is not available in this frontend preview" disabled>Login</Button></div><Button variant="ghost" size="icon" className="lg:hidden" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div>{open&&<div className="border-t border-border bg-background px-5 pb-5 pt-3 lg:hidden"><nav className="flex flex-col" aria-label="Mobile navigation">{nav.map(n=><Link onClick={()=>setOpen(false)} key={n.to} to={n.to} className="border-b border-border py-3 text-sm font-medium">{n.label}</Link>)}<Link onClick={()=>setOpen(false)} to="/directory" className="border-b border-border py-3 text-sm font-medium">Campus directory</Link></nav><form onSubmit={search} role="search" className="mt-4 flex gap-2"><input name="q" aria-label="Search campus resources" placeholder="Search campus resources..." className="h-10 min-w-0 flex-1 rounded-md border border-input bg-background px-3 text-sm"/><Button type="submit" size="icon" aria-label="Search"><Search/></Button></form><p className="mt-4 text-xs text-muted-foreground">Login is not available in this preview.</p></div>}</header>
}
export function SiteFooter(){return <footer className="mt-20 border-t border-border bg-footer text-footer-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 md:grid-cols-2 lg:grid-cols-4"><div className="lg:col-span-1"><Brand inverse/><p className="mt-4 max-w-xs text-sm leading-relaxed text-footer-muted">Your campus, all in one place. Find what matters and make more of every day here.</p><div className="mt-5 flex gap-3 text-footer-muted"><span title="Instagram" aria-label="Instagram"><Instagram size={17}/></span><span title="LinkedIn" aria-label="LinkedIn"><Linkedin size={17}/></span><span title="GitHub" aria-label="GitHub"><Github size={17}/></span></div></div><div><h2 className="text-sm font-semibold">Explore</h2><div className="mt-4 flex flex-col gap-3 text-sm text-footer-muted"><Link to="/events">Events</Link><Link to="/clubs">Student clubs</Link><Link to="/announcements">Announcements</Link></div></div><div><h2 className="text-sm font-semibold">Campus</h2><div className="mt-4 flex flex-col gap-3 text-sm text-footer-muted"><Link to="/resources">Study resources</Link><Link to="/directory">Campus directory</Link><Link to="/search" search={{q:''}}>Search</Link></div></div><div><h2 className="text-sm font-semibold">Get in touch</h2><p className="mt-4 text-sm leading-relaxed text-footer-muted">Have a question? Reach out to your campus student affairs office.</p><Link to="/directory" className="mt-4 inline-flex items-center gap-1 text-sm font-semibold">Find campus services <ArrowUpRight size={16}/></Link></div></div><div className="border-t border-footer-line px-5 py-5 text-center text-xs text-footer-muted">© {new Date().getFullYear()} CampusFlow. Made for campus life.</div></footer>}
export function PageHeader({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <div className="border-b border-border bg-secondary"><div className="mx-auto max-w-7xl px-5 py-12 sm:px-8 sm:py-16"><p className="mb-3 text-xs font-semibold uppercase text-primary">{eyebrow}</p><h1 className="max-w-3xl font-display text-4xl font-semibold leading-tight sm:text-5xl">{title}</h1><p className="mt-4 max-w-2xl text-base leading-relaxed text-muted-foreground">{description}</p></div></div>}
