/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ResourcesRouteImport } from './routes/resources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/clubs': typeof ClubsRoute
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/clubs': typeof ClubsRoute
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/clubs': typeof ClubsRoute
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/announcements' | '/clubs' | '/directory' | '/events' | '/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/announcements' | '/clubs' | '/directory' | '/events' | '/resources'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/clubs'
    | '/directory'
    | '/events'
    | '/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ClubsRoute: typeof ClubsRoute
  DirectoryRoute: typeof DirectoryRoute
  EventsRoute: typeof EventsRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ClubsRoute: ClubsRoute,
  DirectoryRoute: DirectoryRoute,
  EventsRoute: EventsRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
